#+OPTIONS: toc:2

* Introduction
For Eliot, Merry Christmas! This page will be continuously updated, so
check back in every once and a while! A PDF version is also available [[file:recipes.pdf][here]].

* Pantry
** Dashi
*** Ingredients
    - 30 grams dried Kombu
    - 30 grams bonito flakes
    - 2 Liters water
*** Instructions
    Combine water and kombu in a saucepan, and bring to a simmer over
    medium heat. Remove from the heat, then add in the bonito flakes,
    and let sit for 5 minutes. Strian off the kombu and bonito and
    discard. The resulting stock can be stored in the fridge for up to
    a week.
* Snacks
** Sourdough Starter Scallion Pancakes
   - Leftover sourdough starter
   - Scallions
   - Sesame Oil
   - Salt
*** Instructions
   Dice scallions, and add to leftover starter and mix to form a
   batter. Heat a pan on medium heat, and pour batter down to form
   pancakes. Cook as you would a pancake.

   In a small bowl, mix together a bit of sesame oil and salt.
   To serve, dip the pancakes in the sauce.
* Lunch
** Chickpea Wraps
*** Ingredients
    - 1 can chickpeas (15 oz)
    - Mayonnaise (1/3 cup)
    - Sriracha (1.5 Tbsp)
    - Cilantro (2 Tbsp)
    - Lemon Juice (1 Tsp)
    - Salt (1/8 Tsp)
    - Large Flour Tortillas (2)
    - Spinach (2 Cups)
    - Carrot (1)
    - Bell Pepper (1/2)
*** Prep
    - Drain chickpeas
    - Thinly dice carrot into strips
    - Cut bell pepper into strips
*** Instructions
    Add drained chickpeas then add them to a bowl with the mayonnaise,
    sriracha, cilantro, lemon juice, and salt. (You may want to start
    with less sriracha and add more to taste if you are sensitive to
    heat). Mash the chickpeas until they are fairly broken down and
    the dressing ingredients have combined.

    To build the wraps, place the tortillas on a work surface and add
    half of the spinach, carrot sticks, bell pepper, and sriracha
    chickpea salad to each one. Fold the sides in toward the center,
    then roll from the bottom up, like a burrito. Serve immediately or
    refrigerate until ready to eat.
* Dinner
** Chickpeas and Orzo
*** Ingredients
    - 1 can chickpeas (15oz)
    - Orzo (2 servings)
    - Shallot (2)
    - Italian Parsley (5 sprigs)
    - Feta Cheese
    - Olive Oil
*** Prep
    - Dice Parsley
    - Crumble feta cheese
    - Drain and rinse chickpeas
*** Instructions
    Boil water, salt, and cook orzo.

    Saute the shallots until they are translucent and begin
    to brown. Then, add the chickpeas and stir, until they are warmed.
    Then, add the orzo and mix. Remove from heat, and add feta cheese
    to taste. Sprinkle with diced parsley.
** Korean Rice Bowls
*** Ingredients
   - 2 Cups Cooked Rice
   - 2 Tbsp Gochujang
   - 4 Tbsp Soy Sauce
   - 1 Tbsp Rice Vinegar
   - 2 Tbsp Water
   - 4 Large Portobello Mushrooms
   - 1 Yellow Onion
   - 1 Cucumber
   - 1 Carrot
   - 2 green onions
   - Sesame Seeds
*** Prep
   - Slice Onion
   - Grate Carrot
   - Slice Cucumber on bias
   - Slice Green Onions on bias
   - Slice Mushrooms in half, then crosswise.
*** Instructions
   First, begin by preparing the Mushroom Marinade. Mix together the
   Gochujang, Soy Sauce, Rice Vinegar, and Water. Add mushrooms to marinade.
   Mix till all the mushrooms are coated, and let stand for 10 minutes.

   Mix together 1Tbsp Rice vinegar, 1 Tsp sugar, and a sprinkle of
   salt. Add cucumber and let stand, occasionally mixing.

   Heat pan with a smal amount of oil on medium-high. Add onions and let cook
   until translucent. Add mushrooms and marinade then cook till sauce
   is somewhat reduced, about 7-9 minutes.

   Prepare rice bowls by laying down rice, adding mushroom/onions,
   then cucumbers, then carrots. Sprinkle with green onion and sesame seeds.

** Sesame Noodles
*** Ingredients
  - 4 scallions, whites and greens separated, thinly sliced
  - 1/2 cup vegetable oil
  - 1 tablespoon crushed red pepper flakes
  - 2 teaspoons sesame seeds
  - 2 teaspoons Sichuan pepper, coarsely chopped
  - 12 ounces thin noodles
  - Kosher salt
  - 1/4 cup tahini (sesame seed paste)
  - 1/4 cup unseasoned rice vinegar
  - 3 tablespoons soy sauce
  - 2 teaspoons toasted sesame oil
  - 1 teaspoon sugar
*** Instructions
    Cook scallion whites, vegetable oil, red pepper flakes, sesame
    seeds, and pepper in a small saucepan over low heat, stirring
    occasionally, until oil is sizzling and scallions are golden
    brown, 12–15 minutes; let chili oil cool in saucepan.

    Meanwhile, cook noodles in a large pot of salted boiling water
    until al dente; drain. Rinse under cold water and drain well.

    Whisk tahini, vinegar, soy sauce, sesame oil, sugar, and 2–3
    tablespoons chili oil (depending on desired heat) in a large bowl;
    season with salt. Add noodles and toss to coat. Top with scallion
    greens and drizzle with more chili oil.
 
** Chicken Paprikish
*** Ingredients
    - 1 Yellow Onion
    - 1 Red Pepper
    - 1/4 Cup Hungarian Sweet Paprika
    - 1 Bay Leaf
    - 1 Cup Chicken Stock
    - 4 Chicken Legs
    - 1/2 Sour Cream
    - Dill
*** Prep
    Slice onions and bell peppers into medium sized slivers. Split
    chicken legs into thighs and drumsticks.
*** Instructions
    Season chicken on all sides with salt and pepper. Heat a small
    amount of high-smokepoint oil in a pan over medium heat. Once the
    oil is hot, add the chicken pieces skin side down and cook without
    disturbing for about 8 minutes. Flip over and cook until the other
    side for about 2 minutes. Move chicken to a plate, and remove all
    but a small amount of fat from the pan.

    Saute onions and red peppers on medium heat for about 7 minutes.
    Add the paprika and cook while stirring rapidly, making sure not
    to let the paprika burn, for 1 minute. Add the stock, and scrape
    up anything stuck to the bottom of the pan. Add the bay leaf, then
    place the chicken in a single layer into the pan, skin side up.

    Place the heat on low, and cover the pan and cook until the
    chicken is tender all the way through, which ought to take about
    30 minutes.

    Once the chicken is cooked, remove it, and add the sour cream into
    the sauce. Stir until it is mixed thoroughly, then readd the
    chicken back in the sauce, turning to coat.

    When serving, garnish with extra sour cream and minced dill.
** Oyakodon
*** Ingredients
    - 1 Cup [[*Dashi][Dashi]]
    - 1 Tbsp Soy Sauce
    - 2 Tbsp Sake
    - 1 Tbsp Sugar
    - 1 Large Onion
    - 340 grams Chicken Thighs
    - 3 Green Onions
    - 4 Eggs
*** Prep
    Slice onions into slivers. Slice Scalions, and divide into 2 piles.
    Thinly slice chicken
*** Instructions
    Combine Dashi, Soy Sauce, Sake, and sugar in a saucepan and bring
    to a simmer over high heat. Stir in onion and cook until the
    onion is just barely tender, about 5 minutes. Add chicken slices
    and cook, stirring occasionally. Continue until chichken is cooked
    through, about 6 minutes. Stir in half of the green onions, and
    season the broth with soy sauce and sugar to taste.

    Reduce heat, maintaining a bare simmer. Beat eggs in a medium
    bowl, and slowly pour the eggs into the pot in a thin, steady
    stream, using chopsticks to control the flow. Cover and cook until
    the eggs are cooked to your liking, which should be in the 1-3
    minute range.

    To serve, place cooked rice in bowls, and top with egg and chicken
    mixture, adding any extra broth to the rice. Garnish with the
    remaining green onions.
* Baking
** Overnight White Bread
  - White Flour (500g)
  - Kosher Salt (14 g)
  - Yeast (1/4 Tsp)
*** Instructions
    Mix together flour and 390 grams of warm water in a bowl until no
    dry flour remains, and let stand covered with a cloth for 30 minutes.

    Next, add the salt and yeast and fold until incorporated. Then,
    gently fold the dough in half 4 or 5 times, or until the dough
    becomes harder to work. Let rest for 30 minutes, and repeat this
    folding process 3 more times, waiting 30 minutes between each.

    Once the folds are complete, let the dough sit overnight covered
    by a towel (roughly 8 to 12 hours).

    Once this bulk rise has completed, turn the dough onto an
    _unfloured_ work surface. Working quickly, grab the right hand
    side of the bread, and fold 2/3ds of the way over. Then, grab the
    left hand side, and do the same. Next, grab the back side of the
    bread and fold over as well. Now, roll the dough towards you until
    the seam is on the bottom. Now, take the dough in both hands and
    rotate it around to form a ball, making sure not to lift it from
    the work surface. Once the outer skin of the dough has built up
    sufficient tension, dust the top with flour until it is no longer
    tacky, and place in a bowl lined with a towel, floured side down.

    Let the dough rest for about 45 minutes. In the mean time, place a
    dutch oven in the oven at 475 degrees, and let it heat up. When
    the resting period is done, quickly turn out the dough onto a
    piece of parchment paper. Score the top using a sharp knife, and
    then lift the parchment paper into the hot dutch oven. Cover and
    let bake for 20 minutes. Once the 20 minutes is up, uncover and
    let bake until the top is a rich brown. Remove, and let cool.
** Sourdough Starter
   To start, mix together a 50/50 blend of whole wheat and white
   flour. Then add warm water slowly and mix, until you reach a batter
   like consistency. Leave in a warm, dark place covered with a paper towel
   for 3 days, checking every day. Around the third day, the starter
   should start to smell a bit funky and fruity, and should have grown
   in size or formed bubbles.

   Once you have cultivated your starter, it is quite easy to use,
   feed, and maintain it. To use, discard all but one tablespoon of
   the starter, and feed again with a 50/50 blend of whole wheat and
   white flour and water, getting it to a batter like consistency.
   Let this develop for 24 hours. You will know it is ready when it
   floats when placed in water.

   For the overnight white loaf, I like to use about 100 grams of
   starter, and reduce the water to about 370 grams.

   Starter is easiest to work with when you get into a rythm, as
   discarded starter will be used in a loaf of bread, and you can feed
   at the same time as making the dough to be ready for the next day.
   However, baking a loaf of bread every day is a big ask, and not
   always realistic! In these cases, you can put the starter in a
   sealed jar in the fridge to make it go dormant. Just make sure to
   check on it every once and a while to make sure it doesn't dry out.

** Japanese Milk Bread
*** Ingredients
**** Roux
    - 20 grams flour
    - 100 grams water
**** Dough
    - 330 grams flour
    - 24 grams sugar
    - 14 grams powdered milk
    - 7 grams salt
    - 4 grams instant yeast
    - 95 grams warm water
    - 1 egg
    - 20 grams butter
*** Instructions
    First, mix together all the dry ingredients from the *Dough*
    section. Then, proceed to make the roux by whisking the flour into
    the water in a small pot. Heat on medium low, stirring
    continuously. It is done when pulling a spatula through it allows
    you to see the bottom.

    Add all the water, egg, and roux to the dry ingredient
    mixture. Mix, then knead until the dough comes together. Then,
    slowly incorporate the butter while kneading, until the dough is
    slightly tacky. Shape the dough into a ball, then place in a
    greased bowl.

    Cover the dough, and let rise for about an hour, or until it has
    roughly doubled in size. Punch down the dough, divide into halves,
    and reshape into balls. Let the dough rest again for 20 minutes on
    the counter.

    Roll out each ball into an elongated elipse, and fold into thirds lengthwise.
    Roll out the dough again in the same manner, then roll the dough
    up into a log.

    Place both rolls in a loaf pan with the seam facing down. Let
    the dough proof, until it has filled up the pan. Bake at 350F for
    35 minutes. Remove from the pan and let cool on a rack.
