name:                blog
version:             0.1.0.0
github:              "totbwf/blog"
license:             BSD3
author:              "Reed Mullanix"
maintainer:          "reedmullanix@gmail.com"
copyright:           "2018 Reed Mullanix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blog#readme>

executables:
  blog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shake
    - slick
    - base >= 4.7 && < 5
    - aeson
    - lens-aeson
    - lens
    - pandoc
    - text
    - binary
    - bytestring
    - containers
    - mustache
    - time
    # Stuff for the file watcher/server
    - Clipboard
    - fsnotify
    - warp
    - wai-app-static
